# Generated by Django 5.1.7 on 2025-04-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='view_count',
            new_name='views_count',
        ),
    ]
